name: flutter_serialport_example
description: Demonstrates how to use the flutter_serialport plugin.

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_serialport:
    path: ../

  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true