name: flutter_serialport
description: Flutter Serial Port
version: 0.0.1
homepage: https://github.com/pvagnozzi/flutter_serialport
repository: https://github.com/pvagnozzi/flutter_serialport
issue_tracker: https://github.com/pvagnozzi/flutter_serialport/issues

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  libserialport: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.serialport.flutter_serialport
        pluginClass: FlutterSerialportPlugin
      ios:
        pluginClass: FlutterSerialportPlugin
      linux:
        pluginClass: FlutterSerialportPlugin
      macos:
        pluginClass: FlutterSerialportPlugin
      windows:
        pluginClass: FlutterSerialportPluginCApi
      web:
        pluginClass: FlutterSerialportWeb
        fileName: flutter_serialport_web.dart

